stages: 
   - build
   - deploy
   - clean

cache:
   paths:
      - "build"
      - "node_modules"

job build:
   stage: build
   image: node:latest
   script: 
      - npm install
      - npm run build
   only:
      refs: 
         - master
   
job deploy:
   stage: deploy
   image: andreysenov/firebase-tools
   variables:
      REACT_APP_VERSION: $CI_COMMIT_TAG
   script:
      - firebase deploy --token $FIREBASE_TOKEN
   only:
      refs: 
         - master

job clean:
   stage: clean
   script:
      - rm -rf build
   only:
      refs: 
         - master
   when: on_success
      