stages: 
   - build
   - deploy
   - clean

cache:
   paths:
      - "build"
      - "node_modules"

job build:
   stage: build
   image: node:latest
   variables:
      REACT_APP_VERSION: $CI_COMMIT_TAG
   script: 
      - node install
      - node run build
   only:
      - master
      - tags
   
job deploy:
   stage: deploy
   image: andreysenov/firebase-tools:latest
   script:
      - firebase deploy --token "$FIREBASE_TOKEN"
   only:
      - tags

job clean:
   stage: clean
   script:
      - rm -rf build
   only:
      - master
      - tags
   when: on_success
      