stages: 
   - build
   - deploy
   - clean

cache:
   paths:
      - "build"
      - "node_modules"

job build:
   stage: build
   image: node:latest
   script: 
      - npm install
      - npm run build
   only:
      - tags
   
job deploy:
   stage: deploy
   image: andreysenov/firebase-tools:latest
   variables:
      - REACT_APP_VERSION: $CI_COMMIT_TAG
   script:
      - echo "tag $CI_COMMIT_TAG"
      - echo "version $REACT_APP_VERSION"
      - firebase deploy --token "$FIREBASE_TOKEN"
   only:
      - tags

job clean:
   stage: clean
   script:
      - rm -rf build
   only:
      - tags
   when: on_success
      