export const TYPE_CREATE = 'TYPE_CREATE'
export const TYPE_CREATE_EDIT = 'TYPE_CREATE_EDIT'

export const TYPE_EDIT = 'TYPE_EDIT'
export const TYPE_EDIT_CANCEL = 'TYPE_EDIT_CANCEL'
export const TYPE_UPDATE = 'TYPE_UPDATE'

export const TYPE_DELETE = 'TYPE_DELETE'

export const TYPE_LOAD_DATA = 'TYPE_LOAD_DATA'
export const TYPE_SAVE_DATA = 'TYPE_SAVE_DATA'

export const TYPE_KILL = 'TYPE_KILL'
export const TYPE_SET_RANDOM_TIME = 'TYPE_SET_RANDOM_TIME'

export const TYPE_SIGN_IN_USER = 'TYPE_SIGN_IN_USER'
export const TYPE_SIGN_OUT_USER = 'TYPE_SIGN_OUT_USER'

export const TYPE_SET_USER = 'TYPE_SET_USER'

export const TYPE_GET_ALL_BOSS = 'TYPE_GET_ALL_BOSS'

export const TYPE_CREATE_BOSS = 'TYPE_CREATE_BOSS'

export const TYPE_UPDATE_BOSS = 'TYPE_UPDATE_BOSS'

export const TYPE_KILL_BOSS = 'TYPE_KILL_BOSS'

export const TYPE_DELETE_BOSS = 'TYPE_DELETE_BOSS'

export const TYPE_SET_BOSS_RANDOM_TIME = 'TYPE_SET_BOSS_RANDOM_TIME'

export const TYPE_START_LOADING = 'TYPE_START_LOADING'

export const TYPE_CHECK_LOCAL = 'TYPE_CHECK_LOCAL'

export const TYPE_UPLOAD_LOCAL_TO_CLOUD = 'TYPE_UPLOAD_LOCAL_TO_CLOUD'
export const TYPE_UPLOAD_LOCAL_TO_CLOUD_FAILURE = 'TYPE_UPLOAD_LOCAL_TO_CLOUD_FAILURE'

export const TYPE_DELETE_LOCAL_DATA = 'TYPE_DELETE_LOCAL_DATA'

export const TYPE_SET_AUTH_CHANGING = 'TYPE_SET_AUTH_CHANGING'

export const TYPE_SET_CREATE_DIALOG_VISIBLE = 'TYPE_SET_CREATE_DIALOG_VISIBLE'

export const TYPE_RECEIVE_BOSS_CHANGED = 'TYPE_RECEIVE_BOSS_CHANGED'
export const TYPE_RECEIVE_BOSS_ADDED = 'TYPE_RECEIVE_BOSS_ADDED'
export const TYPE_RECEIVE_BOSS_REMOVED = 'TYPE_RECEIVE_BOSS_REMOVED'

export const TYPE_SET_RANDOM_BOSS = 'TYPE_SET_RANDOM_BOSS'

export const TYPE_APPLY_MEMBER = 'TYPE_APPLY_MEMBER'
export const TYPE_CHECK_MEMBER_STATUS = 'TYPE_CHECK_MEMBER_STATUS'
export const TYPE_SET_MEMBER_STATUS = 'TYPE_SET_MEMBER_STATUS'

export const TYPE_GET_MEMBERS = 'TYPE_GET_MEMBERS'

export const TYPE_UPDATE_MEMBER_STATUS = 'TYPE_UPDATE_MEMBER_STATUS'
export const TYPE_REMOVE_MEMBER = 'TYPE_REMOVE_MEMBER'
export const TYPE_RECEIVE_MEMBER_APPLY = 'TYPE_RECEIVE_MEMBER_APPLY'