export const TYPE_CREATE = 'TYPE_CREATE'
export const TYPE_CREATE_EDIT = 'TYPE_CREATE_EDIT'

export const TYPE_EDIT = 'TYPE_EDIT'
export const TYPE_EDIT_CANCEL = 'TYPE_EDIT_CANCEL'
export const TYPE_EDIT_CONFIRM = 'TYPE_EDIT_CONFIRM'

export const TYPE_DELETE = 'TYPE_DELETE'

export const TYPE_LOAD_DATA = 'TYPE_LOAD_DATA'
export const TYPE_SAVE_DATA = 'TYPE_SAVE_DATA'

export const TYPE_KILL = 'TYPE_KILL'
export const TYPE_SET_RANDOM_TIME = 'TYPE_SET_RANDOM_TIME'

export const TYPE_SORT_DATA = 'TYPE_SORT_DATA'

export const TYPE_SIGN_IN_USER = 'TYPE_SIGN_IN_USER'
export const TYPE_SIGN_IN_USER_FAILURE = 'TYPE_SIGN_IN_USER_FAILURE'
export const TYPE_SIGN_OUT_USER = 'TYPE_SIGN_OUT_USER'
export const TYPE_SIGN_OUT_USER_FAILURE = 'TYPE_SIGN_OUT_USER_FAILURE'

export const TYPE_SET_USER = 'TYPE_SET_USER'

export const TYPE_GET_ALL_BOSS = 'TYPE_GET_ALL_BOSS'
export const TYPE_GET_ALL_BOSS_FAILURE = 'TYPE_GET_ALL_BOSS_FAILURE'

export const TYPE_CREATE_BOSS = 'TYPE_CREATE_BOSS'
export const TYPE_CREATE_BOSS_FAILURE = 'TYPE_CREATE_BOSS_FAILURE'

export const TYPE_UPDATE_BOSS = 'TYPE_UPDATE_BOSS'
export const TYPE_UPDATE_BOSS_FAILURE = 'TYPE_UPDATE_BOSS_FAILURE'

export const TYPE_KILL_BOSS = 'TYPE_KILL_BOSS'
export const TYPE_KILL_BOSS_FAILURE = 'TYPE_KILL_BOSS_FAILURE'

export const TYPE_DELETE_BOSS = 'TYPE_DELETE_BOSS'
export const TYPE_DELETE_BOSS_FAILURE = 'TYPE_DELETE_BOSS_FAILURE'

export const TYPE_SET_BOSS_RANDOM_TIME = 'TYPE_SET_BOSS_RANDOM_TIME'
export const TYPE_SET_BOSS_RANDOM_TIME_FAILURE = 'TYPE_SET_BOSS_RANDOM_TIME_FAILURE'

export const TYPE_START_LOADING = 'TYPE_START_LOADING'

export const TYPE_CHECK_LOCAL = 'TYPE_CHECK_LOCAL'

export const TYPE_UPLOAD_LOCAL_TO_CLOUD = 'TYPE_UPLOAD_LOCAL_TO_CLOUD'
export const TYPE_UPLOAD_LOCAL_TO_CLOUD_FAILURE = 'TYPE_UPLOAD_LOCAL_TO_CLOUD_FAILURE'

export const TYPE_DELETE_LOCAL_DATA = 'TYPE_DELETE_LOCAL_DATA'

export const TYPE_SET_AUTH_CHANGING = 'TYPE_SET_AUTH_CHANGING'

export const TYPE_CREATE_DIALOG_VISIBLE = 'TYPE_CREATE_DIALOG_VISIBLE'
export const TYPE_CREATE_DIALOG_INVISIBLE = 'TYPE_CREATE_DIALOG_INVISIBLE'